set nocompatible
set tabstop=4 softtabstop=4
set expandtab
set smartindent
set relativenumber
set nu
set nohlsearch  "   No highlighting after search is done
set hidden
set noerrorbells
set ignorecase  "   Lower case searches are not case-sensitive
set smartcase   "   Using capital letters while searching makes searches case-sensitive
set noswapfile
set nobackup
set incsearch
set scrolloff=8
set signcolumn=yes
set shell=pwsh
set belloff=all

syntax on

"   Plugins

call plug#begin('~/vimfiles/plugged')
Plug 'morhetz/gruvbox'
call plug#end()

set t_Co=256 "  to enable 256 colors
colorscheme gruvbox

