set nocompatible
set tabstop=4 softtabstop=4
set expandtab
set autoindent
set smartindent
set relativenumber
set nu
set nohlsearch  "   No highlighting after search is done
set hidden
set noerrorbells
set ignorecase  "   Lower case searches are not case-sensitive
set smartcase   "   Using capital letters while searching makes searches case-sensitive
set noswapfile
set nobackup
set incsearch
set scrolloff=8
set signcolumn=yes
set shell=pwsh
set belloff=all
set path+=**    "   Allows for easy file searching within the working directory and its sub-directories
set encoding=utf-8
set wildmenu
set laststatus=2
set noshowmode
set t_Co=256 "  to enable 256 colors
set splitbelow splitright 


"   Plugin installation

call plug#begin('~/vimfiles/plugged')

Plug 'nanotech/jellybeans.vim'
Plug 'itchyny/lightline.vim'
Plug 'preservim/nerdtree'
Plug 'ryanoasis/vim-devicons'
Plug 'ycm-core/YouCompleteMe'
Plug 'ajmwagar/vim-deus'
Plug 'vim-scripts/indentpython.vim'
Plug 'airblade/vim-gitgutter'

call plug#end()

syntax enable
colorscheme apprentice

let g:lightline = {
      \ 'colorscheme': 'apprentice',
      \ }


" Start NERDTree and leave the cursor in it.
autocmd VimEnter * NERDTree
" Close the tab if NERDTree is the only window remaining in it.
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
nnoremap <C-t> :NERDTreeToggle<CR>

filetype plugin on

" Split navigation shortcuts
nnoremap <C-J> <C-W>j
nnoremap <C-K> <C-W>k
nnoremap <C-L> <C-W>l
nnoremap <C-H> <C-W>h

" GitGutter settings
