set nocompatible
set tabstop=4 softtabstop=4
set expandtab
set smartindent
set relativenumber
set nu
set nohlsearch  "   No highlighting after search is done
set hidden
set noerrorbells
set ignorecase  "   Lower case searches are not case-sensitive
set smartcase   "   Using capital letters while searching makes searches case-sensitive
set noswapfile
set nobackup
set incsearch
set scrolloff=8
set signcolumn=yes
set shell=pwsh
set belloff=all
set path+=**    "   Allows for easy file searching within the working directory and its sub-directories
set encoding=utf-8
set wildmenu
set laststatus=2
set noshowmode

syntax on


"   Plugin installation

call plug#begin('~/vimfiles/plugged')

Plug 'nanotech/jellybeans.vim'
Plug 'itchyny/lightline.vim'

call plug#end()

set t_Co=256 "  to enable 256 colors
colorscheme jellybeans

let g:lightline = {
      \ 'colorscheme': 'jellybeans',
      \ }

filetype plugin on

